### ISSUE TITLE
Cardboard VR Split View

### ISSUE THREAD

**Issue by emmanuel-montoya** [kilroy80/flutter_video_360#1]
Do you know how could I implement a Cardboard VR View ?

It would help to start adding value to any app with the VR split view feature.

Regards!

**Comment by kilroy80** [comment]
I'm sorry.
There is no plan to update the feature because I don't know the function in detail.

**Comment by emmanuel-montoya** [comment]
We could have a meeting and I could show you in a simple way what is needed :) Let me finish my master's degree and some personal projects and I could contribute with a pull request for this in a few months ;)
