### ISSUE TITLE
Execution failed for task ':video_360:verifyReleaseResources'.

### ISSUE THREAD

**Issue by AsimIrshad** [kilroy80/flutter_video_360#10]
I am developing a Flutter App, I used this package, It works fine in debug mode but in release mood, it is not working.
and the error is due to this package.

here are the error lines:

AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':video_360:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Hp\.gradle\caches\transforms-2\files-2.1\60c390baf599d0c96fc0b007f73c5962\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by kilroy80** [comment]
Thank you for the bug report. I fixed it
