### ISSUE TITLE
Dispose not working on iOS

### ISSUE THREAD

**Issue by GVAMDaniel** [kilroy80/flutter_video_360#22]
I am loading a controller variable as shown in the example.

```
  void _onVideo360ViewCreated(Video360Controller controller) {
    this.controller = controller;
    this.controller?.play();
  }
```

On Android it works correctly, but on iOS when trying to dispose the controller it does not destroy the controller, so when you start the widget again it loads a new controller, leaving the old one in memory.

**Comment by kilroy80** [comment]
main branch fix it.

https://github.com/kilroy80/flutter_video_360/commit/581b3d28a2c8f247e34b8f35aed8ee2a46261a20

**Comment by GVAMDaniel** [comment]
Great! We will testing and tell you something.
