### ISSUE TITLE
The example project not running on iOS

### ISSUE THREAD

**Issue by hakeem-hamon** [kilroy80/flutter_video_360#3]
`Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    error: Unexpected duplicate tasks:
    1) Target 'video_360' (project 'Pods') has copy command from
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player-Info.plist' to
    '/Users/hakeem/Desktop/flutter_video_360/example/build/ios/Debug-iphonesimul
    ator/video_360/video_360.framework/Swifty360Player-Info.plist'
    2) Target 'video_360' (project 'Pods') has copy command from
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player-Info.plist' to
    '/Users/hakeem/Desktop/flutter_video_360/example/build/ios/Debug-iphonesimul
    ator/video_360/video_360.framework/Swifty360Player-Info.plist'
    warning: no rule to process file
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player.modulemap' of type 'sourcecode.module-map' for
    architecture 'arm64' (in target 'video_360' from project 'Pods')
    warning: no rule to process file
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player.debug.xcconfig' of type 'text.xcconfig' for
    architecture 'arm64' (in target 'video_360' from project 'Pods')
    warning: no rule to process file
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player.release.xcconfig' of type 'text.xcconfig' for
    architecture 'arm64' (in target 'video_360' from project 'Pods')
    warning: no rule to process file
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player.modulemap' of type 'sourcecode.module-map' for
    architecture 'x86_64' (in target 'video_360' from project 'Pods')
    warning: no rule to process file
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player.debug.xcconfig' of type 'text.xcconfig' for
    architecture 'x86_64' (in target 'video_360' from project 'Pods')
    warning: no rule to process file
    '/Users/hakeem/Desktop/flutter_video_360/ios/Classes/Swifty360Player/Swifty3
    60Player/Swifty360Player.release.xcconfig' of type 'text.xcconfig' for
    architecture 'x86_64' (in target 'video_360' from project 'Pods')
`

**Comment by kilroy80** [comment]
1. git repo fetch
2. delete example/ios/Podfile.lock
3. run, pod install
4. xcode run, Runner > bundle identifier name changed, Sigining key used your key

**Comment by hakeem-hamon** [comment]
> * git repo fetch
> * delete example/ios/Podfile.lock
> * run, pod install
> * xcode run, Runner > bundle identifier name changed, Sigining key used your key

deleted Podfile.lock, ran pod install from iOS directory, bundle identifier changed through Xcode , used my own signing key still the issue persists.

**Comment by kilroy80** [comment]
Run iPhone Device. I didn't test it in the simulator.
