### ISSUE TITLE
[Android] Video is not rendered but the sound is playing

### ISSUE THREAD

**Issue by chuyentt** [kilroy80/flutter_video_360#4]
Dear @kilroy80 
Thanks for creating a useful package!
I followed your example, on iOS everything is OK but on Android, only a black screen with sound is playing.

**Comment by kilroy80** [comment]
Bug due to Flutter SDK version upgrade. I'm thinking about a solution.

**Comment by chuyentt** [comment]
> 

I have created a PR

**Comment by kilroy80** [comment]
Thank you PR, But that's not the answer. The upgrade of the flutter version changed the way SurfaceView was implemented. If you check it at the beta branch, it won't work properly.

**Comment by chuyentt** [comment]
> Thank you PR, But that's not the answer. The upgrade of the flutter version changed the way SurfaceView was implemented. If you check it at the beta branch, it won't work properly.

My PR is using Flutter 2.10.4 stable (not beta). I have tested on both iOS and Android, and they all work as expected.
