### ISSUE TITLE
Could not find com.google.android.exoplayer:extension-rtmp:2.12.1.

### ISSUE THREAD

**Issue by AnByron** [kilroy80/flutter_video_360#6]
When I add video_360: ^0.0.3, and run the App, i have the next Issues: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:extension-rtmp:2.12.1.
     Searched in the following locations:
       - [https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-rtmp/2.12.1/extension-rtmp-2.12.1.pom]()
       - [https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-rtmp/2.12.1/extension-rtmp-2.12.1.pom]()
       - [https://storage.googleapis.com/download.flutter.io/com/google/android/exoplayer/extension-rtmp/2.12.1/extension-rtmp-2.12.1.pom]()
     Required by:
         project :app > project :video_360
   > Could not find com.google.android.exoplayer:extension-mediasession:2.12.1.
     Searched in the following locations:
       - [https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-mediasession/2.12.1/extension-mediasession-2.12.1.pom]()
       - [https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-mediasession/2.12.1/extension-mediasession-2.12.1.pom]()
       - [https://storage.googleapis.com/download.flutter.io/com/google/android/exoplayer/extension-mediasession/2.12.1/extension-mediasession-2.12.1.pom]()
     Required by:
         project :app > project :video_360

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at [https://help.gradle.org]()

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sharmilhassan** [comment]
I experienced the same problem this morning:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.12.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.12.1/exoplayer-2.12.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.12.1/exoplayer-2.12.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/android/exoplayer/exoplayer/2.12.1/exoplayer-2.12.1.pom
     Required by:
         project :app > project :video_360
   > Could not find com.google.android.exoplayer:extension-rtmp:2.12.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-rtmp/2.12.1/extension-rtmp-2.12.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-rtmp/2.12.1/extension-rtmp-2.12.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/android/exoplayer/extension-rtmp/2.12.1/extension-rtmp-2.12.1.pom
     Required by:
         project :app > project :video_360
   > Could not find com.google.android.exoplayer:extension-mediasession:2.12.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-mediasession/2.12.1/extension-mediasession-2.12.1.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-mediasession/2.12.1/extension-mediasession-2.12.1.pom
       - https://storage.googleapis.com/download.flutter.io/com/google/android/exoplayer/extension-mediasession/2.12.1/extension-mediasession-2.12.1.pom
     Required by:
         project :app > project :video_360

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Exception: Gradle task assembleDebug failed with exit code 1
